//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PHE_APP_SAS.WEB.Negocio
{
    using System;
    using System.Collections.Generic;
    
    public partial class CursoPersona
    {
        public int IdCursoPersona { get; set; }
        public int IdCurso { get; set; }
        public int IdPersona { get; set; }
        public bool DictaCurso { get; set; }
    
        public virtual Curso Curso { get; set; }
        public virtual Persona Persona { get; set; }
    }
}
