//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PHE_APP_SAS.WEB.Negocio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Curso
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Curso()
        {
            this.CursoPersona = new HashSet<CursoPersona>();
        }
    
        public int IdCurso { get; set; }
        public int IdModalidad { get; set; }
        public int IdTipoCurso { get; set; }
        public int IdCategoria { get; set; }
        public int IdCarrera { get; set; }
        public string Nombre { get; set; }
        public string Duracion { get; set; }
    
        public virtual Carrera Carrera { get; set; }
        public virtual Categoria Categoria { get; set; }
        public virtual Modalidad Modalidad { get; set; }
        public virtual TipoCurso TipoCurso { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CursoPersona> CursoPersona { get; set; }
    }
}
