//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PHE_APP_SAS.WEB.Negocio
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PHE_APPS_SASEntities : DbContext
    {
        public PHE_APPS_SASEntities()
            : base("name=PHE_APPS_SASEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Carrera> Carrera { get; set; }
        public virtual DbSet<Categoria> Categoria { get; set; }
        public virtual DbSet<Curso> Curso { get; set; }
        public virtual DbSet<CursoPersona> CursoPersona { get; set; }
        public virtual DbSet<Modalidad> Modalidad { get; set; }
        public virtual DbSet<Persona> Persona { get; set; }
        public virtual DbSet<TipoCurso> TipoCurso { get; set; }
    
        public virtual ObjectResult<sp_rangoEdades_Result> sp_rangoEdades()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_rangoEdades_Result>("sp_rangoEdades");
        }
    
        public virtual ObjectResult<sp_clasificacionGenero_Result> sp_clasificacionGenero()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_clasificacionGenero_Result>("sp_clasificacionGenero");
        }
    }
}
